### ISSUE TITLE
Azure issue with SignatureMethod namespace

### ISSUE THREAD

**Issue by jasonandrewduncan** [handnot2/esaml#18] opened 2019-03-04 22:25 UTC
Microsoft Azure is responding with success there seems to be a problem in parsing the response.

I've tried changing the metadata.xml file with no luck.

Something seems like it is not standard to me in the Azure response as it is failing to find the requested element using the xpath expression in code; but I cannot spot the issue yet.

We're getting an error in xmerl_dsig.erl on line 168.

I'm going to fork the library just to see if we can get things working by changing a few namespaces; but I also wanted to make you aware and see if you had any ideas or have ran into this before and have a way around it.

Here is a full response from one of our test instance and a link to the MetaData

https://login.microsoftonline.com/0adaa849-fc71-472a-9520-2f0da7f74422/FederationMetadata/2007-06/FederationMetadata.xml

Thanks,

Jason

[sample_azure_response.txt](https://github.com/handnot2/esaml/files/2928572/sample_azure_response.txt)

**Comment by samterrell** [comment] 2019-03-04 23:29
That appears to use the proper xmldsig xmlns...
```xml
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
```
It's just using the xmldsig-more URIs for rsa-sha256 from (RFC6931)[https://tools.ietf.org/html/rfc6931] to identify some extra algorithms that weren't defined in 2000/09/xmldsig. That spec added SHA256 among other things.
```xml
<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
```
It's just a value of an attribute.

Most likely the problem is that SAML response has an assertion signature and not an envelope signature. I just use esaml directly, and there is an option to disable the requirement for envelope signature in the sp_config, I believe?

**Comment by samterrell** [comment] 2019-03-04 23:31
I see samly has an option you can put in config for your IDP: `signed_envelopes_in_resp: false` that would probably fix it for you.

**Comment by samterrell** [comment] 2019-03-04 23:36
FYI, the way to tell an envelope signature from an assertion signature is where the `<Signature />` tag is. If it's directly under `<Response />` they call it an envelope signature. That signature would sign the entire XML doc. If it's directly under `<Assertion />` it's an assertion signature, and only signs data under the `<Assertion />` tag.

I've found envelope signatures the easiest to work with, but I'm guessing everyone has a different experience.

**Comment by jasonandrewduncan** [comment] 2019-03-07 18:31
Thanks, I'll try the samly option out tonight if I have a chance.

**Comment by handnot2** [comment] 2019-03-15 18:14
Sorry for the delayed response. Thanks @samterrell for pitching in.

If you are using `Samly`: `signed_envelopes_in_resp: false`

If you are using `esaml`: The `esaml_sp` record has `idp_signs_envelopes` field. Turn it off.

Can you please confirm if you are able to get past this? Just want to make sure that folks are able to use `esaml`/`Samly` with Azure.

Thanks.

**Comment by handnot2** [comment] 2019-04-21 18:07
Closing. Please reopen if needed.

**Closed by handnot2** 2019-04-21 18:07 UTC
